services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8088:8000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - traefik-proxy
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_ecom_flutter.rule=Host(`api-ecom-flutter.jboureux.fr`)"
      - "traefik.http.routers.api_ecom_flutter.entrypoints=websecure"
      - "traefik.http.routers.api_ecom_flutter.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik-proxy"

  db:
    image: postgres
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  traefik-proxy:
    external: true
